MatAntall = document.getElementById("mat")
VinAntall = document.getElementById("vin")
VinPremiumAntall = document.getElementById("vinPremium")
alkoAntall = document.getElementById("alko")
alkoFriAntall = document.getElementById("alkofri")
alkoFriPremiumAntall = document.getElementById("alkoFriPremium")
selvvalgAntall = document.getElementById("Selvvalg")
